export const ACTIVITIES_LIST_REQUEST = 'ACTIVITIES_LIST_REQUEST';
export const ACTIVITIES_LIST_SUCCESS = 'ACTIVITIES_LIST_SUCCESS';
export const ACTIVITIES_LIST_FAIL = 'ACTIVITIES_LIST_FAIL';

export const ACTIVITIES_SEND_REQUEST = 'ACTIVITIES_SEND_REQUEST';
export const ACTIVITIES_SEND_SUCCESS = 'ACTIVITIES_SEND_SUCCESS';
export const ACTIVITIES_SEND_FAIL = 'ACTIVITIES_SEND_FAIL';


export const ACTIVITIES_DELETE_REQUEST = 'ACTIVITIES_DELETE_REQUEST';
export const ACTIVITIES_DELETE_SUCCESS = 'ACTIVITIES_DELETE_SUCCESS';
export const ACTIVITIES_DELETE_FAIL = 'ACTIVITIES_DELETE_FAIL';