export const COST_LIST_REQUEST = 'COST_LIST_REQUEST';
export const COST_LIST_SUCCESS = 'COST_LIST_SUCCESS';
export const COST_LIST_FAIL = 'COST_LIST_FAIL';

export const COST_SEND_REQUEST = 'COST_SEND_REQUEST';
export const COST_SEND_SUCCESS = 'COST_SEND_SUCCESS';
export const COST_SEND_FAIL = 'COST_SEND_FAIL';

export const COST_DELETE_REQUEST = 'COST_DELETE_REQUEST';
export const COST_DELETE_SUCCESS = 'COST_DELETE_SUCCESS';
export const COST_DELETE_FAIL = 'COST_DELETE_FAIL';

